API Assignment 1
abhishekad/getting-started-with-karate pull request #1
Opened 2022-12-14 12:46 UTC by abhishekad

Implementation of Fetching Post and Comments for user id 1
Added the template and feature file

2022-12-15 04:49 UTC, MSR-K requested changes

2022-12-15 04:49 UTC, mshahrukh2 commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +Feature: jsonPlaceholderTypecode.com
This is not correct  feature description. Please change it something meaningful.

2022-12-15 04:49 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +    Then match fetchedPosts.id == '#number'
Validation missing here for verifying id .

2022-12-15 04:49 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +    And match fetchedPosts.title == '#string'
Few other can also be validated here.

2022-12-15 04:49 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +
Since we are doing API tests , validating one scenario is not enough. Please increase the test coverage.

2022-12-15 04:49 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +    And match fetchedComments.body == '#string'
Same as above

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/user_data.json
> +{
File name is incorrect.

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +
Add more valid and invalid scenarios to increase test coverage.

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/api/jsonPlaceholderTypecode.feature
> +    Then match fetchedPosts.id == userId
what if it return multiple post with  user id 1, will this validation works?

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/templates/jsonPlaceholderTemplates.feature
> +    And def fetchedAlbums = response
Response Status validation is missing in templates. We already discuss on this.

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/workflow/jsonPlaceholderWorkflow.feature
> +      And match fetchPosts.title == newTitle
Get request  for created post validation missing!

2022-12-16 12:20 UTC, MSR-K commented on src/test/java/com/znsio/workflow/jsonPlaceholderWorkflow.feature
> +      And karate.log('response : ' + updatePost)
Get request  for updated post validation missing!

2022-12-19 05:02 UTC, abhishekad commented on src/test/java/com/znsio/user_data.json
> +{
modified

2023-07-13 05:25 UTC, closed without merging